### PR TITLE
Record pystats periodically.

### PR DESCRIPTION
**Pull request by mdboom**
Part of https://github.com/faster-cpython/tools/issues/115

### CODE REVIEW

**Comment by mdboom** [comment]
Sorry -- I should make this a draft.  The plan is this will be a weekly cron action, but I have it set to `pull_request` right now so I can test it.  It's broken by https://github.com/python/cpython/issues/99701 at the moment.

**Comment by mdboom** [comment]
Reverting `Py_SETREF` on its own fixes the segfault.

**Comment by brandtbucher** [comment]
Thanks for working on this! This will be a big win for our workflow (I was just trying to decide if it's worth doing a local stats run today to check up on 3.12).

**Comment by mdboom** [comment]
This *should* be working now, and it would be good to get a review in case anything in the action isn't clear (@ericsnowcurrently, @brandtbucher).  There is no way to fully test the part that adds results to the `ideas` repo until we merge this and let the job run -- I think we just have to merge and cross our fingers.  (Pull requests don't have permissions to add files to the repo, for obvious reasons).

**Review by ericsnowcurrently — APPROVED** [review]
LGTM

I'm not especially familiar with the structure and semantics of GitHub workflow configs, but what you have made sense and nothing jumped out at me as wrong. 🙂

**Pull request merged**
